apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.envVars.app.secret . }}
type: Opaque
stringData: {{ toYaml .Values.appSecretData | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.envVars.fluentBit.secret . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {{ toYaml .Values.secrets.fluentBit | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.envVars.jaeger.secret . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {{ toYaml .Values.secrets.jaeger | nindent 2 }}