kind: Service
apiVersion: v1
metadata:
  name: {{ include "appName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chartLabels" . | nindent 4 }}
    app: {{ include "appName" . }}
    name: {{ include "appName" . }}
  annotations:
    {{- if .Values.containers.app.prometheus.enabled }}
    ...
    {{- end }}
spec:
  ports:
    - name: {{ .Values.containers.app.port }}-{{ .Values.containers.app.protocol | lower }}
      port: {{ .Values.containers.app.port | default 8080 }}
      protocol: {{ .Values.containers.app.protocol | default "TCP" }}
      targetPort: {{ .Values.containers.app.port | default 8080 }}
    - name: {{ .Values.containers.fluentBit.port }}-{{ .Values.containers.fluentBit.protocol | lower }}
      port: {{ .Values.containers.fluentBit.port | default 2020 }}
      protocol: {{ .Values.containers.fluentBit.protocol | default "TCP" }}
      targetPort: {{ .Values.containers.fluentBit.port | default 8080 }}
    - name: {{ .Values.containers.jaeger.port }}-{{ .Values.containers.jaeger.protocol | lower }}
      port: {{ .Values.containers.jaeger.port | default 14271 }}
      protocol: {{ .Values.containers.jaeger.protocol | default "TCP" }}
      targetPort: {{ .Values.containers.jaeger.port | default 14271 }}
  selector:
    app: {{ include "appName" . }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "appChart" . }}
  sessionAffinity: None
  type: {{ .Values.containers.app.serviceType | default "ClusterIP" }}
status:
  loadBalancer: { }
